### ISSUE TITLE
GPL-983	New COG-UK prefix for: Health Services Laboratories (HSL) [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/baracoda#111]
**User story**

GPL-983 | As Operations lead (Sonia G) we need a new New COG-UK prefix for: Health Services Laboratories (HSL) for surge testing samples for the South African variant around London. [RT 717687]

**Who are the primary contacts for this story**
Sonia G
Eduardo RM
Rich C

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] New COG-UK prefix: HSLL.
- [ ] Modify SS parsing to accept RNA plate barodes

**Additional context**
See RT: https://rt.sanger.ac.uk/Ticket/Display.html?id=717687

Samples will be processed in the Tecan, plates arriving with positives only (around 2 plates per day), plate maps will be received by email and SSRs will process the submissions.
Main uncertainty at the moment is barcodes, we are trying to get this information as soon as possible.

**Comment by rl15** [comment]
Link to service: http://baracoda.psd.sanger.ac.uk/static/index.html

**Comment by rl15** [comment]
![Uploading Screenshot 2021-04-19 at 09.27.27.png…]()

**Comment by neilsycamore** [comment]
From Alan K
Planned barcodes (for now) for HSL are VARnnnnnn e.g. VAR000003.

**Comment by harrietc52** [comment]
Emailed Alan for more information
