### ISSUE TITLE
GPL-569 | BUG: Set the COG-UK id for Cambridge-az to 'CAMC'

### ISSUE THREAD

**Issue by rl15** [sanger/baracoda#28]
**Describe the bug**
GPL-569 | BUG: Set the COG-UK id for Cambridge-az to 'CAMC'

**Expected behaviour**
COG UK ids should be CAMC

**Comment by rl15** [comment]
Note was a missed/ misunderstood requirement. Prefix agreed 10th July: https://ssg-confluence.internal.sanger.ac.uk/x/OpoKBg (though hinted at in mail of Friday, 3 July 2020 at 16:46)

**Comment by harrietc52** [comment]
Moved story to crawler https://github.com/sanger/crawler/issues/61 and closing this
