### ISSUE TITLE
DPL-556 Upgrade baracoda to new postgresql version 14.5

### ISSUE THREAD

**Issue by emrojo** [sanger/baracoda#311]
**Describe the Housekeeping**
We have asked systems to upgrade postgresql to newer version because the previous version 9.6 is out of support. This ticket is to check that everything works well with the new version of the database.

What we want to do:

- [ ] Check that data in the upgraded database is the same as in the previous one (connect to every table, see number of rows, visually check some of the data)
- [ ] Create a new script with a set of tests for all endpoints in baracoda. The script should check the time it takes to run every endpoint in following situations:
   - Number of requests: 1, 10, 100 and 1000
   - Prefixes: HT, ALDP, SQPU
- [ ] Run the script in UAT **with the old version of postgresql** so we can have an estimation of times for each endpoint.
- [ ] Deploy baracoda using the new version of postgresql
- [ ] Run the script again in UAT and get the new estimation of times.
- [ ] Create a table with the results comparing both (previous version with new version)
- [ ] Run integration suite to check that baracoda is working with other software (Limber/SS)

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by SujitDey2022** [comment]
Completed
