### ISSUE TITLE
DPL-1097 Add RVI prefix to Baracoda

### ISSUE THREAD

**Issue by neilsycamore** [sanger/baracoda#469]
In order to allow GSU to anonymise flu sample data we would like the prefix "RVI" added to baracoda 

**Who are the primary contacts for this story**
fa16

Relates to [RT797033](https://rt.sanger.ac.uk/Ticket/Display.html?id=797033)

**Comment by dasunpubudumal** [comment]
Tasks:

- [ ] Request and obtain access to view [RT797033](https://rt.sanger.ac.uk/Ticket/Display.html?id=797033).
- [ ] Get the `sequence_name` and `formatter_class` clarified (whether we are reusing an existing sequence, or creating a new one)
- [ ] Attach the prefix `RVI` into the `PREFIXES` list in `baracoda`.

**Comment by dasunpubudumal** [comment]
Verifications in training:

### Returning the last generated SQPT barcode:

```
curl --location 'https://training.baracoda.psd.sanger.ac.uk/barcodes/SQPT/last'
```

Response:
```json
{"barcode":"SQPT-3959-C"}
```

---

### Generating a new RVI barcode:

```
curl --location --request POST 'https://training.baracoda.psd.sanger.ac.uk/barcodes/RVI/new?text=t12
```

Response: 
```json
{
    "barcode": "RVI-111111"
}
```
---
### Returning the last generated RVI barcode:

```
curl --location 'https://training.baracoda.psd.sanger.ac.uk/barcodes/RVI/last'
```

Response:
```json
{
    "barcode": "RVI-111111"
}
```
