### ISSUE TITLE
GPL-692 BUG - Lighthouse - Exceptions from Cog Uk Id creation

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/baracoda#54]
**Describe the bug**
Exceptions being thrown during Baracoda COG UK id creation.

**RT Ticket Number**
na

**To Reproduce**
Seems inconsistent. Several noticed in slack output over last few weeks.

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Additional context**
Example of Exception:
2020-10-12 13:07:04,232 lighthouse.blueprints.plates:47 ERROR Unable to create COG barcodes
Traceback (most recent call last):
 File "/code/lighthouse/blueprints/plates.py", line 45, in create_plate_from_barcode
   centre_prefix = add_cog_barcodes(samples)
 File "/code/lighthouse/helpers/plates.py", line 58, in add_cog_barcodes
   raise Exception("Unable to create COG barcodes")
Exception: Unable to create COG barcodes

**Comment by emrojo** [comment]
Steps to reproduce:
1. Add all setup env variables in file .env
2. Start baracoda in local:
```
docker run --env-file .env -p 8000:8000 --entrypoint gunicorn docker.pkg.github.com/sanger/baracoda/baracoda:master -b 0.0.0.0:8000 --timeout 0 --log-level DEBUG --worker-tmp-dir /dev/shm "baracoda:create_app()"
```
3. Create some testing barcodes
4. Go to localhost:8000/barcodes or any other url not existing in server
5. Try to create testing barcodes again, there is a noticeable delay of 10 seconds

Workaround:
Start baracoda with at least 2 workers:
```
docker run --env-file .env -p 8000:8000 --entrypoint gunicorn docker.pkg.github.com/sanger/baracoda/baracoda:master -b 0.0.0.0:8000 --workers=1 --threads=4 --worker-class=gthread --timeout 0 --log-level DEBUG --worker-tmp-dir /dev/shm "baracoda:create_app()"
```
